---
title: "Resume"
output: html_document
date: '2020-05-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Elle P. Reagan**

4532 Lago Viento

Austin, TX 78734

(512) 925-4101

reaganelle@utexas.edu


**EDUCATION**	


> University of Texas at Austin                                      *Aug 2016 – May 2020*
> Bachelor of Science and Arts in Biology
> Minor in Sociology with a Pre-Health certificate


**EMPLOYMENT**

iAchieve Tutoring, Tutor    *Jan 2015 – Current*

> •Provides help and tutoring services for multiple students in all areas of school

Vector Marketing, Social Media Surveyor                     *May 2018 – Sept 2018*

> •	Used social media platforms to find influencers to promote Vector Marketing with respect to recruitment

Vector Marketing, Office Assistant                                   *Jun 2014 – Sept 2014*

> •	Responsible for maintaining and updating website

> •	Designed and created PowerPoints and various visual aids for region-wide conferences

> •	Assisted with the contact and sign-up for multiple meetings and banquets

**LEADERSHIP**	
Texas Royals, Copywriter Chair

> •	Creates and edits blog posts for Texas Royals and works closely with public relations

Camp Kesem, Camp Counselor

> •	Camp Counselor for kids whose parents have been affected by cancer

> •	Raised over $600 for the organization

Texas Royals, Risk Management Chair

> •	Educate members on alcohol safety and implement a “sober sister
 program
 
Texas Royals, Recruitment Committee

> •	Attended recruitment events and evaluated applications for prospective new members


**VOLUNTEER EXPERIENCE**	
Achieve Manual Physical Therapy, Shadow Position

> •	Cleaned and maintained facility 

> •	Assisted physical therapists and patients during sessions

Addicus Dog Legacy, Foster

> •	Rescued dog from shelter on euthanasia list and provided loving home and recovery space

